name: paper # you probably want to 'snapcraft register <name>'
adopt-info: paper
base: core22 # the base snap is the execution environment for this snap
version: '22.11' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.
#architectures:
#  - build-on: amd64
#    build-for: amd64
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo
contact: soumyadeepghosh2004@zohomail.in

package-repositories:
  - type: apt
    components: [main, multiverse, restricted, universe]
    suites: [kinetic, kinetic-backports, kinetic-security, kinetic-updates]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://security.ubuntu.com/ubuntu
parts:
  paper:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.com/posidon_software/paper.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    meson-parameters:
      - --prefix=/snap/paper/current/usr
    parse-info: [usr/share/metainfo/io.posidon.Paper.metainfo.xml]
    organize:
      snap/paper/current/usr: usr
    build-packages:
      - cmake
      - valac
      - blueprint-compiler
      - python3-gi
    override-pull: |
      craftctl default
      sed "s/version: '1.2.0'/version: '>=1.2.0'/" -i src/meson.build
apps:
  paper:
    command: usr/bin/paper
    common-id: io.posidon.Paper
    extensions: [gnome]
    desktop: usr/share/applications/io.posidon.Paper.desktop
    environment:
      GTK_USE_PORTAL: '1'
