name: paper # you probably want to 'snapcraft register <name>'
adopt-info: paper
base: core22 # the base snap is the execution environment for this snap
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
contact: soumyadeepghosh2004@zohomail.in
environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages

parts:
  paper:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.com/posidon_software/paper.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    meson-parameters:
      - --prefix=/usr
    parse-info: [usr/share/metainfo/io.posidon.Paper.appdata.xml]
    organize:
      snap/paper/current/usr: usr
    build-packages:
      - blueprint-compiler
    override-pull: |
      craftctl default
      sed "s/version: '1.2.0'/version: '>=1.2.0'/" -i src/meson.build
      sed "s|labelled-by: notebook_title;|labelled_by: notebook_title;|" -i src/ui/window/window.blp
      sed "s|labelled-by: icon;|labelled_by: icon;|" -i src/ui/window/notebooks_bar/icon.blp
      sed 's|labelled-by: label;|labelled_by: label;|' -i src/ui/window/sidebar/note_card.blp
      sed 's|described-by: descrption_box;|described_by: descrption_box;|' -i src/ui/window/sidebar/note_card.blp
      sed 's|Icon=@app_id@|Icon=usr/share/icons/hicolor/scalable/apps/io.posidon.Paper.svg|' -i data/app.desktop.in
      sed 's|Icon=@app_id@|Icon=usr/share/icons/hicolor/scalable/apps/io.posidon.Paper.svg|' -i data/editor.desktop.in
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - paper
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gnome-42-2204
      - core22
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "gnome-42-2204-sdk" "core22"; do
      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

slots:
  # for GtkApplication registration
  paper:
    interface: dbus
    bus: session
    name: io.posidon.Paper

apps:
  paper:
    command: usr/bin/io.posidon.Paper
    common-id: io.posidon.Paper
    extensions: [gnome]
    desktop: usr/share/applications/io.posidon.Paper.desktop
    environment:
      GTK_USE_PORTAL: '1'
    plugs:
      - home
